# Generated by Django 4.1.7 on 2023-03-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_status_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_status',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
