# Generated by Django 4.1.7 on 2023-03-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_status_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_status',
            name='cart_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
